---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/data_bags
  environments_path: test/environments

platforms:
  - name: ubuntu-14.04

suites:
  - name: production
    provisioner:
      client_rb:
        environment: services-manager-prod
    run_list:
      - recipe[chef_services_manager::default]
    attributes:
